FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY frontend.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app .
ENTRYPOINT ["dotnet", "frontend.dll"]